In [2]:
import cv2
import numpy as np
import PIL
import pytesseract

In [19]:
## reading image using opencv
img0 = cv2.imread('table1.jpg')

#converting image into gray scale image
img = img0.copy()
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
'''scale_percent = 60 # percent of original size
width = int(gray_img.shape[1] * scale_percent / 100)
height = int(gray_img.shape[0] * scale_percent / 100)
dim = (width, height)
resized_image = cv2.resize(gray_img ,dim)'''
# converting it to binary image by Thresholding

# this step is require if you have colored image because if you skip this part

 # then tesseract won't able to detect text correctly and this will give incorrect result
for j in range(3,6):
    pos_con = []
    list_index = []
    #ret,threshold_img = cv2.threshold(gray_img, 254, 255, cv2.THRESH_OTSU)
    ret,threshold_img = cv2.threshold(gray_img, 228, 255, cv2.THRESH_BINARY)
    kernel = np.ones((j,j))
    #erodesion = cv2.erode(threshold_img,kernel,iterations = 1)
    gradient = cv2.morphologyEx(threshold_img, cv2.MORPH_GRADIENT, kernel)
    #closing = cv2.morphologyEx(threshold_img, cv2.MORPH_CLOSE, kernel)
    # display image
    contours, hierarchy = cv2.findContours(gradient, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

    count = 0
    for i, cnt in enumerate(contours):
          areas_con = cv2.contourArea(cnt)
          x, y, w, h = cv2.boundingRect(cnt)
          pos_con.append((x, y, w, h))
          if (areas_con < 19000 and areas_con > 4000) or (areas_con < 2900 and areas_con > 2000):
                cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
                list_index.append(i)
                count += 1
    print(count)
    print(list_index)
    #cv2.imshow('gray_img', gray_img)
    #cv2.imshow('gradient'+str(j), gradient)
    cv2.imshow('threshold_img'+str(j), img)

    # Maintain output window until user presses a key

    cv2.waitKey(0)

    # Destroying present windows on screen

    cv2.destroyAllWindows()

65
[307, 309, 310, 313, 314, 319, 324, 325, 332, 333, 338, 702, 703, 704, 707, 708, 713, 719, 720, 730, 1153, 1154, 1155, 1156, 1163, 1164, 1168, 1175, 1183, 1526, 1527, 1528, 1531, 1533, 1543, 1544, 1548, 1555, 1924, 1925, 1926, 1929, 1930, 1931, 1935, 1936, 1937, 1940, 2288, 2289, 2294, 2295, 2304, 2305, 2308, 2309, 2312, 2414, 2418, 2422, 2427, 2428, 2432, 2441, 2442]
47
[135, 137, 138, 139, 140, 143, 146, 148, 149, 150, 314, 315, 316, 318, 319, 321, 323, 324, 325, 496, 499, 500, 501, 502, 505, 506, 508, 509, 621, 622, 625, 626, 627, 629, 630, 631, 634, 781, 782, 783, 785, 787, 788, 789, 790, 791, 793]
55
[49, 50, 51, 52, 53, 54, 58, 59, 61, 62, 68, 71, 128, 129, 131, 132, 134, 135, 137, 138, 140, 141, 148, 151, 221, 223, 224, 225, 226, 227, 228, 229, 230, 231, 233, 234, 290, 291, 294, 295, 296, 298, 299, 300, 301, 302, 374, 375, 377, 379, 381, 383, 384, 385, 387]


In [24]:
type(threshold_img)

tuple

In [71]:
print(kernel)

[[1. 1.]
 [1. 1.]]


In [52]:
print(gradient-255)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 0]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
